name: redis_ffi
description: A Dart FFI wrapper for hiredis, the minimalistic C client for Redis.
version: 1.0.0
repository: https://github.com/serverpod/redis_ffi

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.0
  hooks: ^1.0.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  ffigen: ^20.0.0
  lints: ^6.0.0
  redis: ^4.0.0
  test: ^1.25.0
