name: example_flutter
description: "Flutter example for redis_ffi package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter
  redis_ffi:
    path: ../../
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
